### PR TITLE
ZCS-3363: Use single AccountZCS instead of ZWC/ZUC/ZMC/ZTC/ZHC to decrease the maintenance and replace ajax reference with universal

### PR DESCRIPTION
**Pull request by jiteshsojitra**
ZCS-3363: Use single AccountZCS instead of ZWC/ZUC/ZMC/ZTC/ZHC to decrease the maintenance and replace ajax reference with universal.

1. There are 100s of places where either:
- Ajax code is called
- Ajax account is used
- Testcase objective refers to Ajax client

First, we need to replace all the code accordingly for Universal UI selenium tests before we do anything else.

2. We are creating initial account with ZWC (for Ajax), ZUC (for Universal), ZHC, ZTC & ZMT for respective clients but that is just initial account. We just need to have one initial account ZCS otherwise we will end up doing lot of maintenance for same code in Ajax and Universal.

### CODE REVIEW

**Review by singhjitesh — COMMENTED** [review]
Corresponding changes should be done in com.zimbra.qa.selenium.framework.util.ZimbraAccount as well. Has it been done/moved somewhere else? I am not able to see the changes in ZimbraAcount.java

**Comment by jiteshsojitra** [comment]
Agreed those changes are already done but it has other changes also so not to confuse all, kept it separately for port changes code as well; please take a look https://jira.corp.synacor.com/browse/ZCS-3368 (Dynamically select ports for multi-node/single-code environment & remove static reference from configuration). Next review request would be for that after this gets merged.

**Review by singhjitesh — APPROVED** [review]
Still, I feel all the related account changes should have been done in one PR/task. This would provide a better understanding of the change and prevent the build failure till the new commit.

**Comment by jiteshsojitra** [comment]
Agree, had both changes in common file so thought to do in next review request to remove confusion for port changes; sorry for that. Anyhow, already raised review request: https://github.com/Zimbra/zm-selenium/pull/70 - please take a look.

**Pull request closed without merging**
